# Generated by Django 3.0.4 on 2020-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200410_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emai',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
